// Cache version is derived from a build-time content hash (assets/js/build-info.js,
// generated by scripts/build.mjs). When the bundle changes, the hash changes, the
// imported script's bytes change, the browser re-installs this worker, and the old
// cache is purged on activate. Falls back to 'dev' when running unbuilt sources.
let BUILD_HASH = 'dev';
try {
  importScripts('./assets/js/build-info.js');
  if (self.__BUILD_HASH__) BUILD_HASH = self.__BUILD_HASH__;
} catch (e) {
  // build-info.js is absent when serving unbuilt sources; keep the 'dev' cache.
}

const CACHE_NAME = `rpc-${BUILD_HASH}`;

// The app ships as a single bundled module, so this shell list is small and
// stable — adding a new TypeScript module no longer requires editing it.
const ASSETS = [
  './',
  './index.html',
  './diagnostics.html',
  './training-report.html',
  './manifest.json',
  './assets/css/main.css',
  './assets/js/main.js',
  './assets/js/build-info.js',
  './assets/images/icons8-exercise-96.png'
];

self.addEventListener('install', (e) => {
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      // Cache best-effort: a single missing asset must not abort installation.
      Promise.allSettled(ASSETS.map((asset) => cache.add(asset)))
    )
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)));
      await self.clients.claim();
    })()
  );
});

self.addEventListener('message', (e) => {
  if (e.data && e.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') {
    return;
  }

  const requestURL = new URL(e.request.url);
  const isSameOrigin = requestURL.origin === self.location.origin;
  const isNavigation = e.request.mode === 'navigate';

  if (!isSameOrigin) {
    return;
  }

  if (isNavigation) {
    e.respondWith(
      (async () => {
        try {
          const networkResponse = await fetch(e.request);
          if (networkResponse && networkResponse.ok) {
            const cache = await caches.open(CACHE_NAME);
            cache.put(e.request, networkResponse.clone());
          }
          return networkResponse;
        } catch (error) {
          const cachedResponse = await caches.match(e.request);
          return cachedResponse || caches.match('./index.html');
        }
      })()
    );
    return;
  }

  e.respondWith(
    (async () => {
      try {
        const networkResponse = await fetch(e.request);
        if (networkResponse && networkResponse.ok) {
          const cache = await caches.open(CACHE_NAME);
          cache.put(e.request, networkResponse.clone());
        }
        return networkResponse;
      } catch (error) {
        const cachedResponse = await caches.match(e.request);
        return cachedResponse || Response.error();
      }
    })()
  );
});
