FROM mcr.microsoft.com/devcontainers/javascript-node:24-bookworm

# Install additional OS packages if needed
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Set the default user
USER node
